name: unittest on push

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the repo
        uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install packages
        run: pip install -r test/unittest/test_requirements.txt
      - name: Test
        run: bash test/unittest/test_all.sh
